context:
  name: onsas
  version: "0.4.2"

package:
  name: octave-${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/ONSAS/ONSAS.m/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b88c1caefcd82d7393b7d604ddefdc0da5136da0cb8b18587469e066857f352c
  target_directory: ${{ name }}

build:
  number: 0
  noarch: generic
  script: |
    cp ${{ name }}/utils/Makefile ${{ name }}/Makefile
    cp ${{ name }}/utils/poetry.lock ${{ name }}/poetry.lock
    cp ${{ name }}/utils/README.md ${{ name }}/README.md
    tar -czf ${{ name }}-${{ version }}.tar.gz ${{ name }}
    octave -W -H --eval "pkg install -global -verbose ${{ name }}-${{ version }}.tar.gz"

    mkdir -p $PREFIX/bin
    cp $RECIPE_DIR/post-link.sh $PREFIX/bin/.octave-${{ name }}-post-link.sh
    chmod +x $PREFIX/bin/.octave-${{ name }}-post-link.sh

requirements:
  host:
    - octave
  run:
    - octave

tests:
  - script: |
      octave -W -H --eval "\
        pkg list; \
        pkg load ${{ name }}; disp('${{ name }} loaded') \
      "

about:
  homepage: https://github.com/ONSAS/ONSAS.m
  license: GPL-3.0-or-later
  license_file: ${{ name }}/COPYING
  summary: Open nonlinear structural analysis solver for GNU Octave

extra:
  recipe-maintainers:
    - arjxn-py
